exporter:
  enabled: true
  serviceMonitor:
    enabled: true
nats:
  resources:
    requests:
      cpu: 0.3
      memory: 2Gi
    limits:
      cpu: 0.3
      memory: 2Gi
  client:
    portName: tcp

  jetstream:
    enabled: true
    memStorage:
      enabled: true
      size: 2Gi
    fileStorage:
      enabled: false
natsbox:
  enabled: true
