module "gke_cluster_tabnine_install" {
  source                      = "codota/gke-tabnine/google//examples/install"
  project_id                  = var.project_id
  region                      = var.region
  zones                       = var.zones
  prefix                      = var.prefix
  cluster_endpoint            = module.gke_cluster_tabnine.endpoint
  cluster_ca_certificate      = module.gke_cluster_tabnine.ca_certificate
  db_url                      = module.gke_cluster_tabnine.db_url
  db_ca                       = module.gke_cluster_tabnine.db_ca
  db_cert                     = module.gke_cluster_tabnine.db_cert
  db_private_key              = module.gke_cluster_tabnine.db_private_key
  redis_url                   = module.gke_cluster_tabnine.redis_url
  redis_ca                    = module.gke_cluster_tabnine.redis_ca
  organization_id             = var.organization_id
  organization_secret         = var.organization_secret
  organization_name           = var.organization_name
  default_email               = var.default_email
  domain                      = var.domain
  exclude_kubernetes_manifest = var.exclude_kubernetes_manifest
  tabnine_registry_username   = var.tabnine_registry_username
  tabnine_registry_password   = var.tabnine_registry_password
  smtp_pass                   = var.smtp_pass
  smtp_user                   = var.smtp_user
  smtp_host                   = var.smtp_host
  email_from_field            = var.email_from_field
  create_managed_cert         = var.create_managed_cert
}
