name: 'CI'

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    name: 'CI'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: hashicorp/setup-terraform@v1

    - name: Format
      run: terraform fmt -check -recursive

    - name: Validate example
      run:
        cd examples/single-gpu
        terraform init 
        terraform init -backend=false -lockfile=readonly
        terraform validate
      

